print ("Prefix",	"10.0.24.0/24",sep="            ")
print ("AD/Metric",	"110/41",sep="           ")
print ("Next-Hop",	"10.0.13.3",sep="           ")
print ("Last update",	"3d18h",sep="            ")
print ("Outbound", "FastEthernet0/0",sep="           ")
print ("Interface",sep="           ")
